// AUTO-GENERATED - File generated by figma2theme 0.6.5, manual edits may be overwritten
// Figma file: https://www.figma.com/file/S8uIjNVgl8bPpBFqwjWYKK
// File version selected: Latest changes to the file (last updated: 2022-03-22 @ 9:59)
// Generated at: Tue Mar 22 2022 09:59:41 GMT+1000 (Australian Eastern Standard Time)

import React from 'react';
import { createIcon } from '@chakra-ui/icon';
